version: '3.8'

services:

  app:

    build:

      context: ./php

    container_name: laravel_app

    volumes:

      - ./src/src:/var/www

      - ~/.composer:/root/.composer  # Laravel Installerのキャッシュ保持

    working_dir: /var/www

    ports:

      - "9000:9000"

      - "5173:5173"

    depends_on:

      - db

  web:

    image: nginx:stable-alpine

    container_name: laravel_nginx

    ports:

      - "8080:80"

    volumes:

      - ./src/src:/var/www

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:

      - app

  db:

    image: postgres:15

    container_name: laravel_postgres

    restart: always

    environment:

      POSTGRES_DB: laravel

      POSTGRES_USER: laravel

      POSTGRES_PASSWORD: secret

    ports:

      - "5432:5432"

    volumes:

      - pgdata:/var/lib/postgresql/data

volumes:

  pgdata: